### ISSUE TITLE
Roadmap, feature design and feature creep

### ISSUE THREAD

**Issue by trickypr** [fushra/meml#8]
## Context
I have recently read the roadmap created by @KaiTheCEO and I want to make a point about the importance of design and avoiding feature creep. Additionally, these are things that I have been thinking about for some time need to be opened up to the community for comments on the designs and any ways to improve

## Project goals
Fushra MEML currently has the following goals:
 - Simplicity for use
 - Powerful enough to replace react in non-PWA or SPA webpages
 - Correctness and maintainability

These three principles must drive the design of features for Fushra MEML. If they do not it is

1. unlikely for MEML to succeed in the target space
2. going to be incredibly hard to maintain

## Feature design
The following features are in the road map in some form or another but are not designed to my satisfaction.

### Dev and command line tools
**Relevant roadmap item:** Compile lists

To preface this, `memlc`, the current command line tool is not intended for any projects larger than a few pages. There will never be a way to build larger, more complex applications. If we continue to use `memlc` it is likely that users will fall back on writing their own wrappers around it using npm scripts or make files.

What MEML needs is a proper build tool with a good config file and a bunch of automation. #6 is related to the need for hot reload / live reload, meaning some form of dev server. This doesn't fit within the goal of `memlc` "compile MEML files". Instead, I propose building a separate build tool, wrapped around the current MEML core. Such a build tool should:
1. Setup a project without the need to initialize it, for example `[tool] dev` in a specific directory creates the necessary file structure and starts a dev server.
2. Handle dependencies (we will get to this later)
3. Give helpful hints to help a new user along, even if they haven't done just the right thing

### SASS support and other module types
**Relevant roadmap item:** SASS support

MEML core is not intended to be an "everything" compiler. Its job is to compile a meml file and absolutely nothing else. It's job is not to triggure a SASS compiler or a LESS compiler or a typescript compiler or a keter compiler. It's job is to compile MEML. That said, we need some way of using industry standards like SASS and typescript without:
1. Adding very little to meml core
2. Not making Fushra or Fivnex responsive for implementing builds for [insert obscure language here]
3. Allowing the community to add languages that we do not and will never support

This is where I want to steal from both [webpack](https://webpack.js.org/) and [parcel](https://parceljs.org/). From webpack, I propose we steal the idea of "loaders", dependencies that follow a standardized API and compile the code for you. This adds far less bloat to MEML core, allows for greater flexibility to the community and improves maintainability for us. From parcel I want to steal auto installing dependencies. When you include a SASS file, it installs the loader for you and allows you to start using it straight away. This should be part of the dev tool, what ever it ends up being called.

### UI frameworks
**Relevant roadmap item:**  Center attribute, dropdown tags, `--bulma`, `--bootstrap`.

By the same token of the previous item, whilst we may want to support bulma and bootstrap, what happens when the community comes and asks for something else? Do we add support for foundation, uikit, milligram, pure, materialize and tailwind? That seems like feature creep and a lot of effort for us. Instead, we should make something similar to a loader but for frameworks. A way of redefining tags like `dropdown` and adding attributes like `bulma` or `tailwind`.

**Comment by KaiTheCEO** [comment]
I am actually glad you brought this up. I actually was wondering more about this myself and lemme assure you that there is a plan. I want to go over this, point by point.

### Project Goals:
While it is true that MEML is supposed to be minimalistic, it also aims to be extensive. There is a reason both Bulma and Bootstrap (CSS only) are being added as part of MEML itself. We will get to this in a bit. This might add to compile times, but I am sure people will understand the reasoning. I, personally, see a different future for Fushra MEML. Since the official MEML releases will be with compiled languages, and since those will *eventually* be the MAIN versions of MEML, I feel like there has to be a divide here.

Fushra MEML, just, for now, is going to show some slight feature creep. There is a plan, Also remember that in projects, any of them labeled `[OPT]` are 100% optional WANTED features that we can discuss later. Something I feel like we are also forgetting is that MEML is supposed to be modular. 

### Dev / CLI Tools:
This was already the plan. On the [downloads](https://meml.fivnex.co/download) page on the meml website, there is an option for LibMEML, which funny enough is exactly what people want. LibMEML is a way to build custom wrapper tools that 100% comply with the MEML Standards. MEML is not a compiler, it is a language. I feel like you are outright ignoring the fact that MEMLC is just ONE of MANY ways to use MEML, some of which aren't developed yet (hence LibMEML). In its current form, MEMLC just needs to hold the bare-bones features that it was designed with so we can push onwards to LibMEML and further.

### SASS and others
 While I would love to agree here, MEML was designed *specifically* to function with SASS code, and the system was designed to have an option to run the SASS compiler. Adding SASS support by triggering the SASS compiler, and the Keter compiler, nothing else. If you are worried about compile times - which you shouldn't, the only reason MEMLC is this slow is because of JavaScript - then understand that MEML has only ever been designed with SASS and Keter in mind.
 
To make this clear, we will *absolutely not* be responsible for adding anything else. That is what LibMEML and MEML Extensions are designed to do. MEML also was never designed to run under the TypeScript language system.

### Frameworks
I understand the concern, but let's make it clear. If the community wants more, the community builds extensions. Ever heard of a thing called NPM? It gives wanted JavaScript functionality by the community. When the community wants more, extensions are built. We don't need to include obscure or other frameworks at all. 

### To conclude
I see you have a concern, however, I do wanna make it clear that MEML is minimalistic BUT EXTENSIVE. I am not expecting Fushra to do more than keep up with the MEML standard, however part of the standard will be SASS support. If you feel it is wrong to add Bulma, understand it is an optional addition. Two of the three optional things to add are literally position and display attributes, and another to include is minifying. 

I am pushing for in Fushra MEML a base where the official Fivnex MEML system can catch up and then split off and continue from there - while following the standards.

**Comment by KaiTheCEO** [comment]
Clicked the wrong button, I just woke up.
